// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDifBBNZ4Ucpr4gcvUecCEZC5xFPsqaU',
    appId: '1:600716846828:android:c722a2abe4e40636b9e7c9',
    messagingSenderId: '600716846828',
    projectId: 'chatapp-37dd9',
    storageBucket: 'chatapp-37dd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsg4wF1yaNTpFc_PjuLB83jPQVu9wnqlk',
    appId: '1:600716846828:ios:8db9b284a59a4438b9e7c9',
    messagingSenderId: '600716846828',
    projectId: 'chatapp-37dd9',
    storageBucket: 'chatapp-37dd9.appspot.com',
    androidClientId: '600716846828-6o8qa4o2v4nqiv9p0pc0j7s9ekkps6ts.apps.googleusercontent.com',
    iosClientId: '600716846828-jfri8jp5p6eajmhca5dh4i4jvfcnsi96.apps.googleusercontent.com',
    iosBundleId: 'com.example.inside',
  );
}
